---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: egressrules.egress.azure-firewall-egress-controller.io
spec:
  group: egress.azure-firewall-egress-controller.io
  names:
    kind: Egressrules
    listKind: EgressrulesList
    plural: egressrules
    singular: egressrules
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Egressrules is the Schema for the egressrules API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: EgressrulesSpec defines the desired state of Egressrules
            properties:
              action:
                description: FirewallPolicyFilterRuleCollectionActionType enumerates
                  the values for firewall policy filter rule collection action type.
                type: string
              destinationAddresses:
                items:
                  type: string
                type: array
              destinationFqdns:
                items:
                  type: string
                type: array
              destinationPorts:
                items:
                  type: string
                type: array
              nodeSelector:
                items:
                  additionalProperties:
                    type: string
                  type: object
                type: array
              podSelector:
                items:
                  additionalProperties:
                    type: string
                  type: object
                type: array
              protocol:
                items:
                  type: string
                type: array
              ruleCollectionName:
                type: string
              ruleType:
                type: string
              sourceAddress:
                items:
                  type: string
                type: array
              targetFqdns:
                items:
                  type: string
                type: array
              targetUrls:
                items:
                  type: string
                type: array
            required:
            - action
            - protocol
            - ruleType
            type: object
          status:
            description: EgressrulesStatus defines the observed state of Egressrules
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
